# Site settings
author: Ashleigh D Battles
title: Confessions of a tech nerd
header-img: img/home-bg.png
email: blueangel365@gmail.com
copyright_name: Ashleigh D Battles
description: > # this means to ignore newlines until "baseurl:"
  a Quirky Techie
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Abattles89

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
